project_id = "hnmfaovpcaaqelwuzzhz"

[functions.praeceptor-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.praeceptor-api]
verify_jwt = false

[functions.fetch-cybersecurity-news]
verify_jwt = false
